<a href="https://colab.research.google.com/github/cmason30/datascience-funhouse/blob/master/pytorch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

Tensor: 

 - A multi-dimensional array
 - In deep learning, refer to the generalization of vectors and matrices to an arbitrary number of dimensions. (Pretty much seen as a layered matrix model)
 - PyTorch is comparable to NumPy in its use of multi-dimensional arrays
 - Why use PyTorch over NumPy then?
  - PyTorch can run on GPUs, distribute processes to multiple machines, and keep track of graph computations



In [ ]:
a = [1.0, 2.0, 1.0]

In [ ]:
a[0]

1.0

In [ ]:
# Creates a one-dimensional tensor of size 3 fille with 1's
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [ ]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
# Instead of tuple pairing coordinates of a triangle in a python object. 
# You can use PyTorch to store all X coords in an even index and 
# all Y coors in the ood indices


points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
coord1 = float(points[0]), float(points[1])
coord2 = float(points[2]), float(points[3])
coord3 = float(points[4]), float(points[5])

coord3

(2.0, 1.0)

In [ ]:
# A better way

points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points.shape

torch.Size([3, 2])

In [ ]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [ ]:
points[0, 0]

tensor(4.)

In [ ]:
points[2]

tensor([2., 1.])

In [ ]:
img_t = torch.randn(3,5,5) # Shape is channel, row, columns (or 3 matrices of 5x5 shape)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

img_t

tensor([[[ 0.1142, -0.7106,  0.4310, -1.5273, -0.1064],
         [-0.0181, -0.3238, -0.8560,  0.9960, -0.6654],
         [ 0.0378, -1.7541, -1.1225, -1.0888,  1.0097],
         [ 0.0384, -0.8016,  1.5943,  0.5293, -0.3877],
         [ 1.2425, -0.4725, -0.0314, -1.0168, -1.2490]],

        [[ 1.2443, -0.5363,  1.5974,  0.1908, -1.3624],
         [ 0.5497, -0.2931, -0.3645, -0.0279,  1.4376],
         [-0.3764,  0.7151, -0.1302,  1.7392,  0.3579],
         [ 0.7829, -0.9747,  1.5951,  1.3376,  1.0028],
         [-0.0917, -0.3086,  0.1015,  0.1753,  0.7558]],

        [[-0.1357, -0.2243,  1.5758,  1.4705,  0.0029],
         [-0.6686, -0.3641, -1.8329, -0.3444,  0.2592],
         [ 0.4758,  0.7007,  0.2137,  1.4151, -0.0542],
         [-0.4501,  2.4730,  1.6429,  0.5219,  0.7461],
         [-0.0103, -0.2466,  0.2763,  0.1090,  1.0644]]])

In [ ]:
batch_t = torch.randn(2,3,5,5)
batch_t

In [ ]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [35]:
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])